### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#2]
First off all I have to admit that I ran out of time. I can't do everything I want to do anymore within the timeframe I had hoped for, but I will fix everything soon.

**Note!** The development are done in the **dev branch**

**Here is what to do:**

- [ ]  Make sure it's stable (*just playing around and testing for bugs*)

- [ ]  Implement escape sequences for templates incl. revisited template ( *stage 3*)

- [ ]  Make it fail 100% after the specs soon as it's stable

- [x]  Finish column and line counting on nodes

- [ ]  Reduce amount of bitmasks

- [x] Cleanup the code base

**Additional**

- [ ] BigInt (*stage 3 proposal*)

- [ ] Await statement (*V8 experimental*)
