### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#21]
- [ ]  Finish destructuring (adjust bitmasks)

- [ ]  Add support for revisited template (stage 3)

- [x]  Reduce code size with 15 - 20%

- [x]   Finish error tracking

- [x] Tweak the performance

**Comment by KFlash** [comment]
**Work in progress**  The entire parser are re-developed to catch up with latest ECMAScript specs.

**Comment by KFlash** [comment]
Closing. See #38
