### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#3]
I ran out of time, so I can't finish everything within the timeframe I wanted, but it will be fixed as soon as I get time for it.

**Left to do**

- [x] Add escaped sequences and revisited template (*stage 3*)

- [ ] Finish destructuring (*adjust bitmasks*)

- [x] Update object rest spread to latest spec. (*Disallow destructuring*).

- [ ] Finish the last non-failing tests (*acc. TC39*)

- [x] Adjust column and line values a few places

- [ ] Finish error tracking

- [ ] Refactor tests

- [x] Find a way to publish a benchmark test to test for regression

- [ ] Finish token collecting in `nextToken()`

- [ ] Refactor JSX

- [ ] Refactor code and cleanup

- [ ] Fix bugs

**Maybe:**

- [ ] Implement Flow

**Comment by caub** [comment]
Just a note: shouldn't it be [`ConciseBody`](https://github.com/cherow/cherow/blob/master/src/masks.ts#L11)? also there are some 'was parse' typo leftovers

**Comment by KFlash** [comment]
@caub You are correct. Things happened little too fast there :) I fixed it now in the break from my regular job.The change will be up shortly.

**Comment by KFlash** [comment]
Closing this.
