### ISSUE TITLE
TODO - Comment attachment

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#64]
Need to improve the way Cherow collect comments today, and also add a new feature allowing comments to be attached to the node without need for `Escodegen` or similar libraries.

- [x] Add a new `attachComment` option for attaching comments

- [x] Attach the comments on the node at correct locations

- [x] Fix / Avoid the same bugs as found in Esprima / Babylon / ESpree

- [x] Optimize the code

- [x] Add loads of tests to get things right!

- [x] Push to GH and NPM

**Comment by KFlash** [comment]
**Example output after parsing with Cherow: **

```js

// Inner comment parsing
cherow.parseScript(`function x() {
            // Inner comment
        }`, { attach: true })

// Output

{
                  "body": [
                    {
                      "async": false,
                      "body": {
                        "body": [],
                        "end": 61,
                        "innerComments": [
                         {
                            "end": 47,
                            "start": 31,
                            "type": "Line",
                            "value": " Inner comment"
                          },
                        ],
                        "leadingComments": null,
                        "start": 13,
                        "type": "BlockStatement"
                      },
                      "end": 61,
                      "expression": false,
                      "generator": false,
                      "id": {
                        "end": 10,
                        "name": "x",
                        "start": 9,
                        "type": "Identifier"
                      },
                      "params": [],
                      "start": 0,
                      "type": "FunctionDeclaration"
                    },
                  ],
                  "sourceType": "script",
                  "type": "Program"
                }
```

**Comment by KFlash** [comment]
Closing. The code is live on NPM. Still several things to fix before pushing to GH:

**Comment by coreybutler** [comment]
Does this actually exist? I couldn't find it in the code npm code.

**Comment by KFlash** [comment]
It did exist in previous version but because you never know exactly where to put a comment - it was removed. And it was also a perf killer.
I can reconsider adding it back for 2.0 if I can gigure out a good algorithm for it.
What's your use case?

**Comment by coreybutler** [comment]
I'm writing a documentation metadata generator, ultimately producing static JSON representations of the different elements of a library. Comments are used to override specific details and add context to the metadata. 

For example, there is an [EventEmitter](https://github.com/ngnjs/NGN/blob/2.0.0/src/common/eventemitter.js) class. The library's build process ultimately packages this class into a namespace called `NGN`, so users of the library would reference `NGN.EventEmitter` instead of just `EventEmitter`. There's no way Cherow would be able to know this, which is where the comments come into play. Comments also offer a fair amount of inline documentation, relevant to the specific node. 

The important part for my use case is _associating comments with specific nodes_. Comments are written above the node, in either single or multi-line syntax, like [these comments](https://github.com/ngnjs/NGN/blob/2.0.0/src/common/eventemitter.js#L41-L51). The "gotcha" I've come across in similar past efforts is the comment isn't always the immediately preceding line... sometimes a dev will leave a line break between the comment and the code.

My current approach is kludgy. I parse the code twice; once with Cherow and once with a comment parsing module. Associations are created by comparing line numbers between the output of each parser. While Cherow performs very nicely as a component of this solution, the overall solution is complex to maintain/communicate.

Personally, I'd be thrilled if there were a way to associate comments with specific nodes. I liked the idea of having this as an option, or even a separate add-on module. I understand why this wouldn't be ideal as the default, but having the option to knowingly take a performance hit in exchange for this functionality would be a big benefit in my use case.

**Comment by KFlash** [comment]
Have you tried to collect the comments and used a 3rd party code to attach them? Similiar to what Acorn suggest?
I'm out of town ATM, but back in a few days and will try to think about this once more. The main issue is that you can't always know wich AST node you should attach the comment to. 

Recast solved this in a good way and attach comments after done parsing. Maybe you could look at that algorithm?

If  done inline - as I tried before -  you would need two sets of arrays and modify `finishNode` to insert the node for each AST node if you use a algorithm ala babylon / Esprima 2.x. i found this not performant.

Third option is to rely on heavy use of member access or mutual parser flags and that way keep track on where to insert the comment. I never tried it, and I'm afraid it would be very complex... 
And I also doubt it's possible to get this 100% correct because there will allways exist a comment that belong to nothing.

Anyway. I can add this to my v. 2.0 TODO list and look into it once more.

And also feel free to contact me on gitter if you want to discuss this further.

**Comment by coreybutler** [comment]
I'll ping you on gitter for further conversation (will wait until you get back), but for completeness/anyone who lands here from a Google search, I'll post one last reply here.

Yes, the Acorn approach is essentially the one I took. It works, it's just tough for other developers to make changes. That may just be the nature of the beast though. I haven't looked at Recast, so I'll check that out.

I would agree it's unlikely to get this 100% correct for all use cases. Though unusual, nothing is stopping a developer from writing comments below a node or even in a specific line.

One thought that occurred is to identify _possible_ nodes a comment could be associated to, like the node immediately preceding/succeeding a comment. This doesn't completely solve my personal use case, but it would significantly reduce the complexity of what needs to be done after the initial parse. It may not make sense to embed that logic directly in the core Cherow lib, but perhaps some sort of hook system would allow Cherow to be extended? In my use case, and potentially any other custom use case, this would make the code significantly more readable/easier to understand.

For illustration purposes:

```js
commentHandler: function (commentNode, nextNode, priorNode) {
  // Handle the comment using custom logic
  if (nextNode.type === 'ClassDeclaration') {
    nextNode.comments = commentNode
  }
}
```

The advantage of this approach is developers can handle the comment processing logic, so Cherow wouldn't necessarily need an algorithm to automate the association. It also leaves any major performance impact decisions to the developer, so the core Cherow lib doesn't needlessly take a performance hit, nor does it appear to pollute the scope of Cherow.

**Comment by coreybutler** [comment]
I just realized that what I suggested is something Acorn is already doing... precedence?

**Comment by KFlash** [comment]
@coreybutler FYI! I'm back.

**Comment by KFlash** [comment]
@coreybutler I'm finally back on track and started to work on 2.0. I have now added option for a comment handler - `onComment`. What's your other ideas?

**Comment by coreybutler** [comment]
I wound up with a more complex solution than I'd hoped, but it works.

Remember, my use case is generating documentation of OOP-style code ([metadata-generator](https://github.com/ngnjs/documentation-metadata-generator)). I used a build process to extract comments separately from the AST, then combine the output. The effect: it generates metadata based on the AST, allowing inline comments to override/customize as necessary.

I use my own extendable build lib ([productionline](https://github.com/coreybutler/productionline)), which has a [generic text file processor](https://github.com/coreybutler/productionline/blob/master/index.js#L12-L171). I extended [this](https://github.com/ngnjs/documentation-metadata-generator/blob/master/index.js#L102-L193) to support comment extraction. It also identifies which line(s) of code a comment is related to. This is mostly generic, but I wouldn't call the code 100% unopinionated.

So, that's the core of the doc generator. I'd love to see a more elegant solution, but the nature of auto-documentation (as opposed to AST parsing) is complex and nuanced. It's mostly opinion, aside from identifying comment-->LOC relativity. I didn't implement a specific algorithm... pretty much just some simple looping.
