### ISSUE TITLE
Upcoming v. 1.0 version

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#68]
Within a few weeks a final version of Cherow will be pushed to GH. The API have changed, and it will offer options to extend the parser.

**TODO**

- [x] Reduced code size

- [x] Reduced memory usage

- [x] Internal plugin API

- [ ] TypeScript support

- [x] Flow support

- [x] Improved performance

### Location tracking

A new option - `offset` - have been added, and let you attach offset information to each node.

### Plugins

The plugin system have been refactored and now offer a

- Internal plugin API (*jsx, flow, typescript etc*)
- Parameterized plugin system

### Tokenization

- Will be added as an new option - `tokens`. A top-level errors array containing all tokens errors will be attached to the root node (*Program*),

### Tolerant parsing

This is all gone, and will be replaced by a editor mode. Let you use Cherow in any IDE.

### Errors

The error reporting have been extended and supports a few new features. Will be listed soon.

### Comments

How Comments works have changed in the upcoming 1.0 version. And some of this is a BC.

The EcmaScpecs defines [MultiLine](http://www.ecma-international.org/ecma-262/8.0/#prod-MultiLineComment) and [SingleLine](http://www.ecma-international.org/ecma-262/8.0/#prod-SingleLineComment) comments. 
In all opensource parsers this is defined as "*LineComment*" or "*BlockComments*". Even if it's a HTML type of comment, it's also defined as a "LineComment". 

**v. 1.0 will have this comment types:**

- SingleLine
- MultiLine
- HTMLOpen
- HTMLClose
- Shebang

**Comment by KFlash** [comment]
The finale 1.0 will be completed within 8 - 9 days.

**Comment by KFlash** [comment]
Closing. The v. 1.0 is in the 1.0 branch, and need optimizations before merging, but it's done.
